location                    = "uksouth"
resource_group_name         = "mate-azure-task-12"
virtual_network_name        = "vnet"
vnet_address_prefix         = "10.0.0.0/16"
subnet_name                 = "default"
subnet_address_prefix       = "10.0.0.0/24"
network_security_group_name = "defaultnsg"
public_ip_address_name      = "linuxboxpip"
vm_name                     = "matebox"
vm_size                     = "Standard_B2ts_v2"
ssh_key_public              = "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQC3/l8QMkG9FOTKLwsZjUeXieo1kEhXrSUCIXRQ6ZjAepgz8tgZ5DfJhfWseR/cG+Zp3YB88703lEEzcWhvOYCIDy+lpcp40pasFZmmasPGTdIWR7OjO3aYu1XeyB0vx1/WD+Y1QPRDGuIWaiKGdIyG5Oz+cHRN9eesx64acsx3+2haMGxyzr544XhKkeVk5WD6wB9fLZOeStSZdeynWc+DGiA9OwCvyhbmdB/va8ppArlubSGMtF1v/WnWKPJ8Z88OZqRZQ2vUCPxFBYWOUZaBUhHvnAZUXjcwsM3xnmUPitcWoB01J02VZxYVQ7O8YPbYYDzqfauDUNF7BLf8GTUKcUPP5R49hZznrHobvY7K54w9jT14jVEhU7MDTK/YbDAwTLqPtqUkwk5AN3v7boGPbXVnDIXgrkfrSj2BTI073heEQNdAFH8lYXCYFLATk9ZW1X7whl/8TOlziSrbyLLeXuO4k9gMv2BPCwTxxHatkkT+kCJPgYQXc+DcM8eDrsU= generated-by-azure"
dns_label                   = "matetask"
github_repo_url             = "https://github.com/spridoloba/devops_todolist_terraform_task.git"
